services:
    postgres:
        container_name: gocar-postgres
        image: postgres
        restart: always
        environment:
            - DATABASE_HOST=127.0.0.1
            - POSTGRES_USER=dev
            - POSTGRES_PASSWORD=dev
            - POSTGRES_DB=dev
        ports:
            - 5432:5432

    api:
        container_name: gocar-api
        build: .
        environment:
            - PORT=8080
            - POSTGRES_DSN=host=postgres user=dev password=dev dbname=dev port=5432
        ports:
            - "8080:8080"
        depends_on:
            - postgres
